dist: xenial
language: python
python:
  - "2.7"
install:
  - source cfg4dev
  - pip install coveralls
  - docker pull koalaman/shellcheck:latest
script:
  - pip check
  - flake8
  - docker run -v "$PWD:/mnt" koalaman/shellcheck:latest $(find . -name \*.sh | grep -v \.\/env)
  - travis_fold start "build.python.packages"
  - python setup.py bdist_wheel sdist --formats=gztar
  - travis_fold end "build.python.packages"
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package tor_async_util
after_success:
  - coveralls || true
