dist: xenial
language: python
python:
  - "2.7"
install:
  - source cfg4dev
  - pip install coveralls
  - docker pull koalaman/shellcheck:latest
script:
  - run_pip_check.sh
  - flake8
  - docker run -v "$PWD:/mnt" koalaman/shellcheck:latest $(find . -name \*.sh | grep -v \.\/env)
  - travis_fold start "build.python.packages"
  - python setup.py bdist_wheel sdist --formats=gztar
  - travis_fold end "build.python.packages"
  - run_unit_tests.sh
after_success:
  - coveralls || true
