dist: xenial
language: python
python:
  - "2.7"
install:
  - source cfg4dev
  - pip install coveralls
  - docker pull koalaman/shellcheck:latest
script:
  - run_pip_check.sh
  - run_flake8.sh
  - run_shellcheck.sh -v
  - run_repo_security_scanner.sh
  - travis_fold start "build.python.packages"
  - build_python_package.sh
  - travis_fold end "build.python.packages"
  - run_unit_tests.sh
after_success:
  - coveralls || true
