language: python
python:
  - "2.7"
install:
  - source cfg4dev
  - pip install coveralls
script:
  - pep8
  - flake8
  - python setup.py sdist --formats=gztar
  - nosetests --with-coverage --cover-branches --cover-erase
after_success:
  - coveralls || true
